### ISSUE TITLE
Using customMessage with custom username and icon_url

### ISSUE THREAD

**Issue by milani** [slackhq/hubot-slack#187]
I use the following code to send a customMessage to Slack. 
```
robot.emit 'slack-attachment', {
  channel: "test",
  attachments: [{color:"#4183C4",title: "Test",text:"this is a test."}],
  username: "CustomBotName",
  icon_url: "http://path/to/an/icon.png",
  text: ""
}
```
Everything works except the `username` and `icon_url`. A default icon and bot name ("bot") appears on Slack. Is there anything I'm missing or it's a bug?

**Comment by chrisatomix** [comment]
Same problem, looks like the fix for this was in #162 but it hasn't been pushed to NPM (it's still showing a version from February).

I've changed the dependencies in my package.json from:
```json
"hubot-slack": "^3.3.0",
```
to:
"hubot-slack": "slackhq/hubot-slack",
```
and now it uses the latest version from Github. Getting a few build errors in the logs (to do with the "ws" module in slack-client) but it seems to be working.

I modified a few scripts (including yours) to test this, it seems to be working now:
```coffeescript
robot.emit 'slack-attachment',
  channel: "general"
  username: "CustomBotName"
  icon_url: "https://slack.global.ssl.fastly.net/9fa2/img/services/hubot_128.png"
  content:
    fallback: "fallback"
    title: "works now"
    title_link: "https://github.com"
    text: "Shows up"
    image_url: "https://assets-cdn.github.com/images/modules/logos_page/GitHub-Logo.png"
    color: "#111111"
```
