### ISSUE TITLE
Slack client closed, waiting for reconnect

### ISSUE THREAD

**Issue by robertmircea** [slackhq/hubot-slack#203]
I've noticed that Hubot disconnects from Slack after a period of inactivity. I'm seeing this message in log but after that nothing happens and hubot no longer appears connected in Slack channels. At that point, only a manual restart will do.

[Sun Jun 21 2015 09:27:39 GMT+0300 (EEST)] INFO Slack client now connected
[Sun Jun 21 2015 09:29:36 GMT+0300 (EEST)] INFO Slack client closed, waiting for reconnect

How hubot-slack suppose to recover from this this state?

**Comment by impleri** [comment]
Perhaps related, but I'm in a similar boat. Log messages:

````
[Sat Jul 04 2015 13:42:17 GMT+0000 (UTC)] ERROR Last pong is too old: 10.005
[Sat Jul 04 2015 13:42:17 GMT+0000 (UTC)] INFO Reconnecting in 1000ms
[Sat Jul 04 2015 13:42:18 GMT+0000 (UTC)] INFO Attempting reconnect
[Sat Jul 04 2015 13:42:18 GMT+0000 (UTC)] INFO Connecting...
[Sat Jul 04 2015 13:42:38 GMT+0000 (UTC)] INFO Logged in as hubot of TEAM, but not yet connected
[Sat Jul 04 2015 13:42:38 GMT+0000 (UTC)] INFO Slack client closed
````

**Comment by ptierno** [comment]
Also experiencing the `Last pong is too old:` error. :+1:

**Comment by drags** [comment]
Seeing this as well: 

    INFO Slack client closed, waiting for reconnect


Turned on debugging, the last action before the disconnect (by 10m 50s) was emitting a `slack-attachment` that looked like:

```
robot.emit 'slack-attachment',
  channel: res.message.user.name
  username: robot.name
  icon_url: 'https://slack.global.ssl.fastly.net/9fa2/img/services/hubot_128.png'
  content:
    fallback: "A thing #{thing}"
    title: my_title
    text: "```<~15 lines>```"
    mrkdwn_in: ['text']
    color: '#111111'
```

Including the slack-attachment since it seems to frequently be the last thing in the logs
